const quotes = [
    "The best way to get started is to quit talking and begin doing.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "The only way to do great work is to love what you do.",
    "Believe you can and you're halfway there.",
    "Opportunities don't happen. You create them.",
    "Don't watch the clock; do what it does. Keep going.",
    "Quality means doing it right when no one is looking.",
    "It always seems impossible until it’s done.",
    "Do what you can, with what you have, where you are.",
    "Act as if what you do makes a difference. It does.",
    "Don’t let yesterday take up too much of today.",
    "Keep going. Everything you need will come to you at the perfect time.",
    "Difficult roads often lead to beautiful destinations.",
    "Dream big, work hard, stay focused, and surround yourself with good people.",
    "What we fear doing most is usually what we most need to do.",
    "It’s not whether you get knocked down, it’s whether you get up.",
    "Great things are done by a series of small things brought together.",
    "The man who moves a mountain begins by carrying away small stones.",
    "Go confidently in the direction of your dreams. Live the life you have imagined.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "I find that the harder I work, the more luck I seem to have.",
    "Failure is the opportunity to begin again more intelligently.",
    "You miss 100% of the shots you don’t take.",
    "I never dream of success. I work for it.",
    "Start where you are. Use what you have. Do what you can.",
    "The way to get started is to stop talking and start doing.",
    "Doubt kills more dreams than failure ever will.",
    "Push yourself, because no one else is going to do it for you.",
    "Some people dream of success, while others wake up and work hard at it.",
    "A journey of a thousand miles begins with a single step.",
    "Don’t be afraid to give up the good to go for the great.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Work hard in silence, let success make the noise.",
    "Make each day your masterpiece.",
    "You don’t have to be great to start, but you have to start to be great.",
    "I never lose. I either win or learn.",
    "The secret of getting ahead is getting started.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Your limitation—it’s only your imagination.",
    "Work until your idols become your rivals.",
    "There are no limits to what you can accomplish, except the limits you place on your own thinking.",
    "The best revenge is massive success.",
    "Energy and persistence conquer all things.",
    "Never give up, because great things take time.",
    "Take risks: if you win, you will be happy; if you lose, you will be wise.",
    "I am not a product of my circumstances. I am a product of my decisions.",
    "Don’t wait for opportunity. Create it.",
    "Perseverance is not a long race; it is many short races one after another.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Your time is limited, so don’t waste it living someone else’s life."
];

function generateQuote() { 
    let randomIndex = Math.floor(Math.random() * quotes.length);
    document.getElementById("quote").innerText = quotes[randomIndex];
}
